[package]
name = "graphical_pathfinding"
version = "0.4.5"
authors = ["Ray Britton <raybritton@gmail.com>"]
edition = "2018"

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
ggez = "0.5.1"